language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - pip install tox
script:
  - export TOX_ENV=`echo $TRAVIS_PYTHON_VERSION | sed -E 's/^([0-9])\.([0-9])$/py\1\2/'`
  - tox -e $TOX_ENV
