sudo: false
language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4.0'; fi
  - pip install coveralls 
  - pip install .
script:
  - coverage run --branch --source=configy setup.py -q test
after_success: 
  - coveralls
